mock: file_downloader: fix pylint errors
Error: PYLINT_WARNING:
mock/py/mockbuild/file_downloader.py:15: C0115[missing-class-docstring]: FileDownloader: Missing class docstring

Error: PYLINT_WARNING:
mock/py/mockbuild/file_downloader.py:40:15: R1729[use-a-generator]: FileDownloader.get: Use a generator instead 'any(pkg.startswith(pfx) for pfx in url_prefixes)'

Error: PYLINT_WARNING:
mock/py/mockbuild/file_downloader.py:55:14: W3101[missing-timeout]: FileDownloader._get_inner: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely

Error: PYLINT_WARNING:
mock/py/mockbuild/file_downloader.py:67:8: E1137[unsupported-assignment-operation]: FileDownloader._get_inner: 'cls.backmap' does not support item assignment