configs: fix rawhide config after branching
We forgot to bump releasever in afbadca68a4d4bf304feebc98 and it is
needed because all f35 packages are being re-signed with F35 keys we are
not referencing, errors:

Public key for openssl-libs-1.1.1i-3.fc35.x86_64.rpm is not installed. Failing package is: openssl-libs-1:1.1.1i-3.fc35.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-34-primary, file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-34-primary, file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-33-primary
Error: GPG check FAILED