Fix for race in directory creation [BZ# 1052045]
When starting several instances of mock at the same time and root_cache
plugin is used and /var/cache/mock is empty there is a race condition
and only first mock runs successful and other fails with:

ERROR: Could not create dir /var/cache/mock/fedora-20-i386/root_cache/. Error: [Errno 17] File exists: '/var/cache/mock/fedora-20-i386/root_cache/'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 69, in mkdirIfAbsent
    os.makedirs(dirName)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)

mkdirIfAbsent doesn't catch situation where directory is created by
other instance.

Add logic to the exception clause to catch directory existence.

Signed-off-by: Clark Williams <clark.williams@gmail.com>