bootstrap-chroot: always explicitly install shadow-utils
Previously we only did this explicitly for yum_install_command,
apparently because yum itself (even transitively) never depended on
shadow-utils.

But 'dnf' package has stopped depending on shadow-utils as well [1]
(dnf -> systemd -> shadow-utils) so we need to be explicit in
{micro,}dnf_install_command as well.

Per error:
Finish(bootstrap): dnf install
ERROR: Could not find useradd in chroot, maybe the install failed?

[1] https://src.fedoraproject.org/rpms/dnf/c/faa199f16041940b85012fb8456b2fca349b6f9e?branch=master

Fixes: rhbz#1743843