Fix --dnf-cmd traceback
We need to first `commands.init()` before we access the
buildroot.pkg_manager, per:

    log.info('Running %s %s', buildroot.pkg_manager.command, ' '.join(args))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'command'

Found-by: #1082