Fix "init_install_output" error
This error:

  AttributeError: 'Buildroot' object has no attribute 'init_install_output'

can occur because init_install_output is initialized in the pkg_manager object but not in the buildroot object.