Hotfix preexec_fn traceback on RHEL 8 s390x
It was pretty complicated to debug (we can not easily see tracebacks
from subprocess when we set stdout/err to subprocess.PIPE and handling
those streams by logOutput() too late, the output is not delivered);
with the help of traceback.print_exc(), I caught the error in
ChildPreExec.__call__(), and it looked like:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 821, in __call__
    log = getLog()
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 520, in condUnshareIPC
    logger.info("Child dead, killing orphans")
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 461, in unshare
    # https://github.com/rpm-software-management/mock/issues/113
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 22, in __init__
    # works around problem where reconfiguring the logging module means loggers
  File "/usr/lib64/python3.6/inspect.py", line 1478, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/lib64/python3.6/inspect.py", line 1452, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib64/python3.6/inspect.py", line 828, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range

Which looks like a Python bug caused by Mock bug -- doing getLog()
inside the preexec_fn is not expected to work probably (child process
has different file descriptors than what parent configured).

But since we don't have a definitive answer from Python team, and we
need to release a new version soon - let's comment-out the logOutput()
to fix Mock on EL8.s390x.

Relates: #653
Merges: #655