scm: python3 does not treat binary string as array
addressing:
Traceback (most recent call last):
  File "/usr/sbin/mock", line 828, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 650, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 663, in run_command
    (options.sources, options.spec) = scmWorker.prepare_sources()
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/scm.py", line 154, in prepare_sources
    if "--exclude-vcs" in proc.communicate()[0]:
TypeError: Type str doesn't support the buffer API