mock: print stdout/stderr if 'install_srpm' failed
It is kind of strange to use returnOutput=True here when we don't
actually use the output in caller, but this parameter also causes that
the raised exception (in case of command failure) contains both stderr
and stdout.  As a result, mock ends with very clear error:

    /usr/bin/systemd-nspawn -q -M 0f25244d38ab4d32a46a109813628224 -D
    ... all the nspawn args ....
    /bin/rpm -Uvh --nodeps /builddir/build/originals/python-copr-1.100-1.git.36.dff5221.fc31.src.rpm
    error: Missing rpmlib features for python-copr-1.100-1.git.36.dff5221.fc31.noarch:
    error:  rpmlib(DynamicBuildRequires) <= 4.15.0-1
    error: /builddir/build/originals/python-copr-1.100-1.git.36.dff5221.fc31.src.rpm cannot be installed

Instead of:

    /usr/bin/systemd-nspawn -q -M 0f25244d38ab4d32a46a109813628224 -D
    ... all the nspawn args ....
    /bin/rpm -Uvh --nodeps /builddir/build/originals/python-copr-1.100-1.git.36.dff5221.fc31.src.rpm

Fixes: #461