mock: ceanup rpmdb before checking installed packages
In doChroot we do the same, before we call host's rpm against chroot
rpmdb.  We need to do the same in all_chroot_packages().  This caused
problems on EL7 when building packages dynamic BuildRequires in new
chroots (Fedora 31+):

    ERROR: Command failed:
     # /bin/rpm -qa --root /var/lib/mock/fedora-rawhide-x86_64/root

Very likely we'll have to invent new doChroot()-like abstraction to
automatically call such RPM commands either from host (bootstrap
disabled) or from bootstrap chroot (bootstrap enabled), issue #525.