Handle exceptions from command_parse() method
That way we print e.g. just:
ERROR: The --localrepo option works only with --chain

Instead of ugly traceback:
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1027, in <module>
    (opts, packages) = command_parse()
  File "/usr/libexec/mock/mock", line 413, in command_parse
    raise mockbuild.exception.BadCmdline(
mockbuild.exception.BadCmdline: The --localrepo option works only with --chain

And we also return the correct exit status 5 for BadCmdline.