Revert "R: 79, 4: Method could be a function (no-self-use)"
This reverts commit eb99792dcc2a2f148afebaf525b7b8a40276f337.

Breaks traceLog:
  File "[...]/mock/py/mockbuild/trace_decorator.py", line 60, in trace
    filename = os.path.normcase(inspect.getsourcefile(func))
  File "/usr/lib64/python3.4/inspect.py", line 571, in getsourcefile
    filename = getfile(object)
  File "/usr/lib64/python3.4/inspect.py", line 536, in getfile
    'function, traceback, frame, or code object'.format(object))
TypeError: <classmethod object at 0x7fcc423cd358> is not a module, class, method, function, traceback, frame, or code object