mock: check for qemu-user-static to raise InvalidArchitecture()
This specific error is better handled by upper Mock's code;  e.g. we
don't raise the ugly traceback:

INFO: Unable to build arch armv7hl natively on arch x86_64. Setting forcearch to use software emulation.
ERROR: The --forcearch=armv7hl feature requires the /usr/bin/qemu-arm-static file to be installed (typically qemu-user-static* package)
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1087, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 709, in main
    check_arch_combination(config_opts['rpmbuild_arch'], config_opts)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 565, in check_arch_combination
    raise RuntimeError(
RuntimeError: The --forcearch=armv7hl feature requires the /usr/bin/qemu-arm-static file to be installed (typically qemu-user-static* package)