tests: do not skip tests upon --scrub failure
The #1586 introduced broken config files:
$ mock -r alma-kitten+epel-10-x86_64_v2 --scrub=all
ERROR: Could not find included config file: /etc/mock/almalinux-kitten-10-x86_64_v2.cfg

It doesn't make sense to skip the testing in this situation.