yum_init_install_output does not exist
This was silently hidden for 2 years. Removing the try/except as well so we see the error when it happen.

addressing:
AttributeError: 'Buildroot' object has no attribute 'yum_init_install_output'